config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    mount ActionCable.server => "/cable"
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/show", to: "users#show"
    get "/signup", to: "users#new"

    resources :products
    resources :users
    resources :orders
    resources :rooms

    namespace :admin do
      resources :categories
      resources :products
      resources :users
      resources :orders
      resources :rooms
      resources :payment_methods
      get "/profit", to: "charts#profit"
    end

    resources :account_activations, only: %i(edit)
    resources :password_resets, only: %i(new create edit update)
    resources :carts, only: %i(index) do
      collection do
        post "add_to_cart/:id", to: "carts#add_to_cart", as: "add_to"
        delete "remove_from_cart/:id", to: "carts#remove_from_cart", as: "remove_from"
        post "update_cart", to: "carts#update_cart", as: "update_to"
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true).paginate(page: params[:page], per_page: 8)
    # @products = Product.last(8)
  end

  def help; end
end

app/views/static_pages/_header.slim
.center.top
  #slider
    .slide
      img src="https://i.imgur.com/erYH1cO.jpg" stt="0"
      img src="https://i.imgur.com/04UFsit.jpg" stt="1" style="display:none;"
      img src="https://i.imgur.com/FEO5IeF.jpg" stt="2" style="display:none;"
      img src="https://i.imgur.com/kNJJRUS.jpg" stt="3" style="display:none;"
  a.clickL  ❮
  a.clickR  ❯
  .content
    h1 
      span= t("static_pages.header.welcome")
      b Shopppi
    - if logged_in?
      = link_to products_path
        span
        span
        span
        span
        = t("static_pages.header.show_all_product")
    -else
      = link_to signup_path
        span
        span
        span
        span
        = t("sessions.new.sign_up_now")
.new-products
  h1= t("static_pages.header.product_new")
  - @products.each do |product|
      .card2
        =link_to product, class: "detail" do
          - if product.images.attached?
            .image 
              = image_tag product.images.first
          - else 
            .image 
              img src="https://www.w3schools.com/w3images/jeans3.jpg" alt="Denim Jeans"
        =link_to product, class: "detail" do
          .name.text
            h3 = product.name
        .price
          p = product.price.to_s + " $"
        =link_to t("static_pages.header.add_to_cart"), add_to_carts_path(id: product.id, quantity: 1), method: :post, class: "btn btn-primary btn-cart"

app/views/static_pages/_product.slim
= render "products/form"
.all_products
  = render @products
.paginate
  = will_paginate @products

app/views/static_pages/contact.slim
- provide(:title,t("layouts.footer.contact"))
h1= t("layouts.footer.contact")
p.center.lead.mb-5= t("static_pages.contact.introduction_contact")
.row
  .col-md-6.col-md-offset-3
    .form-group
      = label_tag "Name", t("carts.index.name")
      = text_field_tag "name", nil, class: "form-control"
    .form-group
      = label_tag "Email"
      = text_field_tag "email", nil, class: "form-control"
    .form-group
      = label_tag "Message", t("static_pages.contact.message")
      = text_area_tag "message", nil, class: "form-control", rows: 5
    .form-group
      = button_tag t("static_pages.contact.send"), type: "button", class: "btn btn-success w-50"
      = button_tag t("static_pages.contact.cancel"), type: "button", class: "btn btn-default w-50"

app/views/static_pages/home.html.slim
.center.jumbotron
    h1 
        |Welcome to the 
        b Shopppi
    = link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" 

app/views/static_pages/home.slim
- if logged_in? 
  - if current_user.is_admin?
    .container-fluid
      .row
        .col-sm-3.sidebar
          = render "layouts/dashboard"
        .col-sm-9
          = render 'static_pages/header'
  - else
    = render 'static_pages/header'
- else
  = render 'static_pages/header'