config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    mount ActionCable.server => "/cable"
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/show", to: "users#show"
    get "/signup", to: "users#new"

    resources :products
    resources :users
    resources :orders
    resources :rooms

    namespace :admin do
      resources :categories
      resources :products
      resources :users
      resources :orders
      resources :rooms
      resources :payment_methods
      get "/profit", to: "charts#profit"
    end

    resources :account_activations, only: %i(edit)
    resources :password_resets, only: %i(new create edit update)
    resources :carts, only: %i(index) do
      collection do
        post "add_to_cart/:id", to: "carts#add_to_cart", as: "add_to"
        delete "remove_from_cart/:id", to: "carts#remove_from_cart", as: "remove_from"
        post "update_cart", to: "carts#update_cart", as: "update_to"
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
  end
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  has_many :orders
end

app/controllers/admin/payment_methods_controller.rb
module Admin
  class PaymentMethodsController < ApplicationController
    before_action :set_payment_method, only: %i[edit update destroy]

    def index
      @payment_methods = PaymentMethod.all.paginate(page: params[:page], per_page: 10)
    end

    def edit; end

    def update
      if @payment_method.update(payment_method_params)
        flash[:success] = t("flash.success.update")
        redirect_to admin_payment_methods_path
      else
        render :edit
      end
    end

    def new
      @payment_method = PaymentMethod.new
    end

    def create
      @payment_method = PaymentMethod.new(payment_method_params)
      if @payment_method.save
        flash[:success] = t("flash.success.payment_method_created")
        redirect_to new_admin_payment_method_path
      else
        render :new
      end
    end

    def destroy
      return unless @payment_method.destroy

      flash[:info] = t("flash.info.deleted")
      redirect_to admin_payment_methods_path
    end

    private

    def set_payment_method
      @payment_method = PaymentMethod.find_by_id(params[:id])
      return unless @payment_method.nil?

      flash[:danger] = t("flash.danger.payment_method_not_found")
      redirect_to admin_payment_methods_path
    end

    def payment_method_params
      params.require(:payment_method).permit(:name)
    end
  end
end

app/views/admin/payment_methods/_form.slim
.row
  .col-md-6.col-md-offset-3
    = form_for([:admin, @payment_method]) do |f|
      = f.label :name, t("admin.payment_methods.form.payment_method_name"), class: "form-label"
      = f.text_field :name, class: 'form-control'
      = f.submit t("admin.categories.form.add"), class: "btn btn-primary mt-3"

app/views/admin/payment_methods/_payment_method.slim
tbody
  tr
    td= payment_method.name
    td
      button.CN.edit
        = link_to t("users.user.edit"), edit_admin_payment_method_path(payment_method)
        i.fa.fa-pencil-square
      button.CN.delete
        = link_to t("carts.index.delete"), admin_payment_method_path(payment_method), method: :delete
        i.fa.fa-trash-o

app/views/admin/payment_methods/edit.slim
h1= t("payment_methods.edit.title")
= render 'form'

app/views/admin/payment_methods/index.slim
.row.ml-0
  .col-sm-3.sidebar
    = render "layouts/dashboard"
  .col-sm-9
    h1= t("admin.payment_methods.index.title")
    button.CN.new
      = link_to new_admin_payment_method_path
        i.fa.fa-plus-circle
        span= t("admin.payment_methods.index.add_payment_method")
    table.table.table-condensed
      thead
        tr
          td
            b= t("carts.index.name")
          td
            b= t("categories.index.modify")
      = render @payment_methods
    .paginate 
      = will_paginate @payment_methods

app/views/admin/payment_methods/new.slim
h1= t("admin.payment_methods.new.title")
br
= render 'form'

app/views/admin/payment_methods/show.slim
- if @payment_methods.present?
  table.table.table-condensed
    thead
      tr
        td
          b= t("carts.index.name")
        td
          b= t("categories.index.modify")
    = render @payment_methods
- else 
  p= t("payment_methods.show.no_payment_method")
.paginate 
  = will_paginate @payment_methods