config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    mount ActionCable.server => "/cable"
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/show", to: "users#show"
    get "/signup", to: "users#new"

    resources :products
    resources :users
    resources :orders
    resources :rooms

    namespace :admin do
      resources :categories
      resources :products
      resources :users
      resources :orders
      resources :rooms
      resources :payment_methods
      get "/profit", to: "charts#profit"
    end

    resources :account_activations, only: %i(edit)
    resources :password_resets, only: %i(new create edit update)
    resources :carts, only: %i(index) do
      collection do
        post "add_to_cart/:id", to: "carts#add_to_cart", as: "add_to"
        delete "remove_from_cart/:id", to: "carts#remove_from_cart", as: "remove_from"
        post "update_cart", to: "carts#update_cart", as: "update_to"
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
  end
end

app/controllers/carts_controller.rb
require "cart"

class CartsController < ApplicationController
  before_action :check_empty_cart, only: %i[index remove_from_cart]
  before_action :load_line_item, only: %i[add_to_cart remove_from_cart]
  before_action :update_quantity, only: [:update_cart]

  def index
    @cart_items = load_line_items_in_cart
  end

  def add_to_cart
    if @item
      @item["quantity"] += params[:quantity].to_i
      flash[:info] = t("flash.info.add") + "#{params[:quantity]} #{@product.name}" + t("flash.info.to_cart")
    else
      images = []
      @product.images.each do |img|
        images << url_for(img)
      end
      current_cart << { product_id: @product.id, name: @product.name, price: @product.price,
                        quantity: params[:quantity].to_i, images: images }
      flash[:success] = t("flash.success.added") + "#{params[:quantity]} #{@product.name}" + t("flash.info.to_cart")
    end
    session[:cart] = current_cart
    redirect_to root_path
  end

  def remove_from_cart
    return unless @item

    flash[:info] = t("flash.info.removed") + "#{@item["quantity"]} #{@item["name"]}" + t("flash.info.from_cart")
    current_cart.delete(@item)
    session[:cart] = current_cart
    redirect_to carts_path
  end

  def update_cart
    current_cart.each do |item|
      (0..@length - 1).each do |i|
        item["quantity"] = @quantity_item[i].to_i if item["product_id"] == params[:item_carts][i.to_s]["id"].to_i
      end
    end
    session[:cart] = current_cart
    redirect_to carts_path
  end

  private

  def check_empty_cart
    return unless session[:cart].nil?

    redirect_to root_path
    flash[:info] = t("flash.info.empty_cart")
  end

  def load_line_item
    @product = Product.find_by(id: params[:id])
    if @product
      @item = find_product_in_cart @product
    else
      redirect_to root_path
    end
  end

  def update_quantity
    @item_carts = params[:item_carts]
    @quantity_item = []
    @length = @item_carts.keys.length
    (0..@length - 1).each do |item_cart|
      @quantity_item << @item_carts[item_cart.to_s]["quantity"] if item_cart
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    session[:cart] ||= []
  end

  def find_product_in_cart(product)
    current_cart.find { |item| item["product_id"] == product.id }
  end

  def load_line_items_in_cart
    cart_items = []
    current_cart.each do |item|
      product = Product.find_by_id(item["product_id"])
      if product
        cart_items << { product: product, quantity: item["quantity"], images: item["images"] }
      else
        current_cart.delete(item)
      end
    end
    cart_items
  end

  def subtotal(item)
    item[:product].price * item[:quantity]
  end

  def total_price
    items = load_line_items_in_cart
    items.reduce(0) { |a, e| a + e[:product].price * e[:quantity] }
  end
end

app/views/carts/index.slim
- provide(:title, t("carts.index.my_cart"))
h1 = t("carts.index.my_cart")
table.table.table-bordered
  thead.bg-primary
    tr
      th.text-center = t("carts.index.product")
      th.text-center = t("carts.index.image")
      th.text-center = t("carts.index.price")
      th.text-center = t("carts.index.quantity")
      th.text-center = t("carts.index.total")
      th.text-center
  tbody
    - @cart_items.each do |item|
      tr
        td.w-25
          .product-name
            = item[:product].name
        td.text-center.w-20
          .product-thumbnail
            - if item[:images].blank?
              img.img-fluid alt="image-product" src="https://www.w3schools.com/w3images/jeans3.jpg"
            - else
              img.img-fluid alt="image-product" src= item[:images][0]
        td.text-center.w-15
          .cart-price id="price-#{item[:product].id}"
            = item[:product].price.to_s + " $"
        = form_with do |f|
          td.text-center.w-15
            = f.button "Sub", class: "btn btn-default sub-btn", data: { id: "#{item[:product].id}" }, type: "button" do
              i.fa.fa-minus
            = f.text_field "quantity", value: item[:quantity], class: "text-center form-control number-input cart-quantity", id: "cart_#{item[:product].id}"
            = f.button "Add", class: "btn btn-default add-btn", data: { id: "#{item[:product].id}" }, type: "button" do
              i.fa.fa-plus
        td.w-15
          .fw-bold.cart-subtotal id="subtotal-#{item[:product].id}"
            = subtotal(item).to_s + " $"
        td.text-center.btn-action
          =link_to remove_from_carts_path(id: item[:product].id), method: :delete, class: "btn btn-danger btn-cart" do
            span = t("carts.index.delete")
            i.fa.fa-trash
  tfoot.bg-info
    tr
      td.text-center.fw-bold colspan="4" = t("carts.index.total")
      td.fw-bold colspan = "2"
        span#total-price
          = total_price.to_s + " $"
.pb-3.pt-3
  = link_to t("carts.index.continue"), root_path, class: "btn btn-primary mr-5"
  = button_tag t("carts.index.update"), class: "btn btn-success btn-update mr-5", data: { items: @cart_items.map { |item| item[:product] } }, method: :post, remote: true
  = link_to t("carts.index.order"), new_order_path, class: "btn btn-success"