config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    mount ActionCable.server => "/cable"
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/show", to: "users#show"
    get "/signup", to: "users#new"

    resources :products
    resources :users
    resources :orders
    resources :rooms

    namespace :admin do
      resources :categories
      resources :products
      resources :users
      resources :orders
      resources :rooms
      resources :payment_methods
      get "/profit", to: "charts#profit"
    end

    resources :account_activations, only: %i(edit)
    resources :password_resets, only: %i(new create edit update)
    resources :carts, only: %i(index) do
      collection do
        post "add_to_cart/:id", to: "carts#add_to_cart", as: "add_to"
        delete "remove_from_cart/:id", to: "carts#remove_from_cart", as: "remove_from"
        post "update_cart", to: "carts#update_cart", as: "update_to"
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many_attached :images
  belongs_to :order_detail
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :category_products, dependent: :destroy
  has_many :categories, through: :category_products

  validates :code, presence: true
  validates :name, presence: true
  validates :price, presence: true, format: { with: /\A\d{1,6}(\.\d{0,2})?$\z/ }, numericality: { only_integer: true }
  validates :description, presence: true

  scope :ordered_by_name, -> { order(name: :desc) }
  scope :ordered_by_price, -> { order(name: :desc) }
  scope :search_name, ->(name) { where("name LIKE ?", "%#{name}%") if name.present? }
  scope :search_category, ->(category_ids) { where(category_ids: category_ids) if category_ids.present? }
  scope :search_product, lambda { |params|
    search_name(params[:name])
      .search_category(params[:category_ids])
  }
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < AdminsController
    before_action :set_product, only: %i[edit update destroy]

    def index
      @category = Category.find_by_id(params[:category_id])
      @products = if @category
                    @category.products.all
                             .search_product(params)
                             .paginate(page: params[:page], per_page: 10)
                             .ordered_by_price
                  else
                    Product.search_product(params)
                           .paginate(page: params[:page], per_page: 10)
                           .ordered_by_price
                  end
    end

    def edit; end

    def update
      if @product.update(product_params)
        flash[:success] = t("flash.success.profile_update")
        redirect_to admin_products_path
      else
        render "edit"
      end
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        flash[:success] = t("flash.success.product_created")
        redirect_to new_admin_product_path
      else
        render "new"
      end
    end

    def destroy
      return unless @product.destroy

      flash[:info] = t("flash.info.deleted")
      redirect_to admin_products_path
    end

    private

    def set_product
      @product = Product.find_by_id(params[:id])
      return if @product

      flash[:info] = t("flash.info.product_not_found")
      redirect_to admin_products_path
    end

    def product_params
      params.require(:product).permit(:name, :code, :price, :description, category_ids: [], images: [])
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
                  .paginate(page: params[:page], per_page: 8)
                  .ordered_by_price
  end

  def show
    @product = Product.find_by_id(params[:id])
    return if @product

    flash[:info] = t("flash.info.product_not_found")
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :code, :price, :description, :category_ids, images: [])
  end
end

app/views/admin/products/_form_new.slim
.form-new.w-50
  = form_for ([:admin, @product]) do |f|
    = render 'shared/error_messages', object: f.object 
    = f.label "Code", t("admin.categories.show.code"), class: "form-label"
    = f.text_field :code, class: "form-control"
    = f.label "Name", t("carts.index.name"), class: "form-label"
    = f.text_field :name, class: "form-control"
    = f.label "Price", t("carts.index.price"), class: "form-label"
    = f.text_field :price, class: "form-control"
    = f.label "Description", t("admin.categories.show.description"), class: "form-label"
    = f.text_area :description, :rows => 6, class: "form-control"
    = f.label "Categories", t("products.index.category"), class: "form-label"
    = f.collection_select :category_ids, Category.all, :id, :name, {include_blank: "Select Category"}, {class: "form-control form-select-sm custom-select"}
    br
    = f.label "Images", t("carts.index.image"), class: "form-label"
    = f.file_field :images, multiple: true, class: "form-control"
    br
    = f.submit class: "btn btn-primary"

app/views/admin/products/_product.slim
tbody   
  tr
    td.code
      = product.code
    td.email
      = product.name
    td.email
      = product.price
    td.text
      p = product.description
    td.image
      - if product.images.attached? 
        - product.images.each do |image| 
            = image_tag(url_for(image))
      - else 
        img src="https://www.w3schools.com/w3images/jeans3.jpg" alt="Denim Jeans"
    td.chucNang
      button.CN.edit
        = link_to edit_admin_product_path(product)
          i.fa.fa-pencil-square
      button.CN.delete
        = link_to admin_product_path(product) , method: :delete, data: { confirm: t("admin.products.product.confirm") + product.name }
          i.fa.fa-trash-o

app/views/admin/products/_search_form.slim
= form_tag admin_products_path, method: :get do
  .search-products
    p
      = text_field_tag :name, params[:name], placeholder: t("admin.products.search.name_product"), class: "form control search"
      = collection_select(nil, :category_id, Category.all, :id, :name, prompt: true, class: "filter-search")
      = submit_tag t("layouts.header.search"), :name => nil, class: "btn btn-success search"

app/views/admin/products/edit.slim
h1= t("admin.products.edit.edit_product")
= render "form_new"

app/views/admin/products/index.slim
.row.ml-0
  .col-sm-3.sidebar
    = render "layouts/dashboard"
  .col-sm-9
    h1  =t("products.index.product")
    button.CN.new
      = link_to new_admin_product_path(@product)
        i.fa.fa-plus-circle
        span= t("products.new.new_product")
    = render "search_form"
    table.table.table-condensed
      thead
        tr
          td
            b= t("admin.categories.show.code")
          td
            b= t("carts.index.name")
          td
            b= t("carts.index.price")
          td
            b= t("admin.categories.show.description")
          td
            b= t("carts.index.image")
          td
            b= t("admin.categories.index.modify")
      = render @products
    .paginate 
      = will_paginate @categories

app/views/admin/products/new.slim
h1= t("admin.products.new.new_product")
= render "form_new"